### ISSUE TITLE
Ruby Vs JavaScript

### ISSUE THREAD

**Issue by sammyhenningsson** [digital-fabric/modulation#5]
I do understand the reason for this. When I started coding Perl 10ish years ago I struggled with understanding from where things actually originated. But nowadays that's not something that troubles me any more. If you write Ruby the way it's meant to be written then I don't think you find the library useful.
Ruby is truly object oriented and is best organized that way. (Yes it is really easy and nice to write functional code, but IMHO I think those functions should be properly encapsulated in object oriented code).
I recommend reading [Practical Object-Oriented Design, An Agile Primer Using Ruby (POODR)](https://www.poodr.com/) to get a deeper understanding of how Ruby is best written.

**Comment by noteflakes** [comment]
> If you write Ruby the way it's meant to be written then I don't think you find the library useful.

And who decides how Ruby code is to be written? you? Ruby can do lots of different things, and thankfully the Ruby community is diverse and inclusive, and gladly accepts boundary-pushing projects and experiments that drive Ruby forward. Also note that the kind of Ruby code written today is already much different than that written 10 or 15 years ago.

> I recommend reading Practical Object-Oriented Design, An Agile Primer Using Ruby (POODR) to get a deeper understanding of how Ruby is best written.

I'm sure you were writing in good faith, but your "recommendation" comes across as condescending and frankly a bit offensive. If you have specific remarks regarding the [*actual code*](https://github.com/digital-fabric/modulation/tree/master/lib) of this project, I'll be happy to be enlightened.

Finally, comments about the validity of this project do not belong here. I'll gladly accept such comments in a setting such as reddit or HN, rather than on the Modulation issue tracker. Please keep the discussion technical and on point.

**Comment by sammyhenningsson** [comment]
Sorry for offending you. I do find this project interesting, very well-written and I hope people get inspiration from the code. I just wish that people would appreciate the beauty of objected oriented code in Ruby and never even consider bloating `Object`.
